"""
YAML snippet generator for the reTerminal Dashboard Designer integration.

This module takes the internal layout model (DeviceConfig / PageConfig / WidgetConfig)
and produces ESPHome-compatible YAML snippets that the user can paste BELOW an
existing base ESPHome config.

Key principles:
- We DO NOT emit:
  - esphome:
  - esp32:
  - wifi:
  - api:
  - ota:
  - logger:
- We ONLY emit additive blocks:
  - globals, fonts, outputs, rtttl, sensors, text_sensors, scripts, display, etc.
- We target the reTerminal E1001 epaper (800x480) as the initial device.

The output is a single YAML snippet string containing:
- Header comments explaining how to use it.
- Behavior/config blocks (buttons, scripts, etc).
- Layout block(s) mapping configured pages/widgets to display lambda code.

NOTE: This is an MVP generator:
- Focus on safe, deterministic output.
- Supports a conservative subset of widget types.
- Uses IDs and structures inspired by the working reference in:
  resources/ESPHome Reterminal/reterminalE-1001-esphome.txt
"""

from __future__ import annotations

from typing import List

from .models import DeviceConfig, PageConfig, WidgetConfig
from .const import IMAGE_WIDTH, IMAGE_HEIGHT


SNIPPET_HEADER = """# ============================================================
# Generated by reTerminal Dashboard Designer
# Target device: reTerminal E1001 (800x480 epaper)
#
# Usage:
# 1. Ensure you already have a working base ESPHome config for your device:
#    - Includes: esphome, esp32, wifi, api, ota, logger
#    - Uses the correct board for the reTerminal E1001
# 2. Paste this snippet BELOW your existing base config.
# 3. Do NOT duplicate esphome:, wifi:, api:, ota:, logger: sections.
# 4. If you already define conflicting ids (e.g. epaper_display), adjust accordingly.
#
# WARNING:
# - This is an MVP generator. Review the result before flashing.
# - Keep this snippet under version control to track your layout changes.
# ============================================================
"""


def generate_snippet(device: DeviceConfig) -> str:
    """
    Generate a complete YAML snippet for the given device configuration.

    The snippet includes:
    - Required globals/fonts/outputs/rtttl/buttons/sensors/scripts for navigation.
    - A display: epaper_display block with lambda that renders all pages/widgets.

    This function assumes:
    - Single device_type: reTerminal E1001.
    - IMAGE_WIDTH/IMAGE_HEIGHT match the target display (800x480).
    """
    device.ensure_pages()

    parts: List[str] = [SNIPPET_HEADER.rstrip(), ""]

    # Core pieces (ordered for readability)
    # NOTE: output, rtttl, sensor, time are provided by hardware template
    # We only generate: globals, fonts, text_sensor, button, script, display
    parts.append(_generate_globals())
    parts.append(_generate_fonts(device))  # Pass device to collect icon glyphs
    parts.append(_generate_text_sensors(device))  # Only text_sensors for HA entities
    parts.append(_generate_navigation_buttons(device))
    parts.append(_generate_scripts(device))
    parts.append(_generate_display_block(device))

    # Join with double newlines between major sections
    return "\n\n".join(p for p in parts if p.strip())


def _generate_globals() -> str:
    return """globals:
  # Current page index (0-based)
  - id: display_page
    type: int
    restore_value: true
    initial_value: '0'

  # Battery icon glyph (optional usage in display lambda)
  - id: battery_glyph
    type: std::string
    restore_value: no
    initial_value: "\\U000F0079"

  # Default page refresh interval (seconds)
  - id: page_refresh_default_s
    type: int
    restore_value: no
    initial_value: '900'
"""


def _generate_fonts(device: DeviceConfig) -> str:
    """
    Generate font definitions including Material Design Icons fonts for icon widgets.
    Collects all icon codes from the device and generates appropriate MDI fonts.
    """
    # Collect all unique icon codes from icon widgets
    icon_codes = set()
    for page in device.pages:
        for widget in page.widgets:
            wtype = (widget.type or "").lower()
            if wtype == "icon":
                props = widget.props or {}
                code = props.get("code", "").strip()
                if code:
                    icon_codes.add(code)
    
    # Base fonts (Inter)
    font_lines = [
        "font:",
        "  - file: \"gfonts://Inter@400\"",
        "    id: font_small",
        "    size: 19",
        "",
        "  - file: \"gfonts://Inter@500\"",
        "    id: font_normal",
        "    size: 22",
        "",
        "  - file: \"gfonts://Inter@700\"",
        "    id: font_header",
        "    size: 24"
    ]
    
    # Add MDI fonts if there are icon widgets
    if icon_codes:
        # Convert codes to Unicode escapes
        glyphs = []
        for code in sorted(icon_codes):
            # code is like "F0595" - convert to "\U000F0595"
            glyphs.append(f'"\\U000{code}"')
        
        glyph_list = ", ".join(glyphs)
        
        font_lines.extend([
            "",
            "  # Material Design Icons for icon widgets",
            "  # Copy materialdesignicons-webfont.ttf to your ESPHome fonts folder",
            "  - file: fonts/materialdesignicons-webfont.ttf",
            "    id: font_mdi_medium",
            "    size: 48",
            f"    glyphs: [{glyph_list}]"
        ])
    
    return "\n".join(font_lines)


# Removed _generate_outputs_and_buzzer() - now in hardware template


def _generate_text_sensors(device: DeviceConfig) -> str:
    """
    Generate ONLY text_sensor blocks for HomeAssistant entities used in sensor_text widgets.
    sensor: section is now in the hardware template.
    """
    # Collect all unique entity_ids from sensor_text widgets
    entity_ids = set()
    for page in device.pages:
        for widget in page.widgets:
            wtype = (widget.type or "").lower()
            if wtype in ("sensor", "sensor_text"):
                entity_id = (widget.entity_id or "").strip()
                if entity_id:
                    entity_ids.add(entity_id)
    
    if not entity_ids:
        return "# No sensor_text widgets configured - no text_sensor section needed"
    
    # Build text_sensor entries for each unique entity
    text_sensor_entries = []
    for entity_id in sorted(entity_ids):
        # Create a safe ID from entity_id (replace dots with underscores)
        safe_id = entity_id.replace(".", "_").replace("-", "_")
        text_sensor_entries.append(f"""  - platform: homeassistant
    id: {safe_id}
    entity_id: {entity_id}
    internal: true""")
    
    return f"""text_sensor:
{chr(10).join(text_sensor_entries)}
"""


def _generate_navigation_buttons(device: DeviceConfig) -> str:
    # Template buttons for navigation and refresh.
    # These operate on display_page and let HA/ESPHome automations drive page changes.
    return """button:
  - platform: template
    name: "reTerminal Next Page"
    id: reterminal_next_page
    on_press:
      - lambda: |-
          int pages = {pages};
          id(display_page) = (id(display_page) + 1) % pages;

  - platform: template
    name: "reTerminal Previous Page"
    id: reterminal_prev_page
    on_press:
      - lambda: |-
          int pages = {pages};
          id(display_page) = (id(display_page) - 1 + pages) % pages;

  - platform: template
    name: "reTerminal Refresh Display"
    id: reterminal_refresh_display
    on_press:
      - component.update: epaper_display
""".format(
        pages=len(device.pages)
    )


def _generate_scripts(device: DeviceConfig) -> str:
    """
    Generate time + manage_run_and_sleep script with per-page refresh support.

    Semantics:
    - A global default interval (page_refresh_default_s).
    - Inline switch(page) using PageConfig.refresh_s values when provided.
    - Enforce a minimum of 60 seconds for any effective interval.
    """
    case_lines: List[str] = []
    for idx, page in enumerate(device.pages):
        refresh = getattr(page, "refresh_s", None)
        if refresh is None:
            continue
        try:
            val = int(refresh)
        except (TypeError, ValueError):
            continue
        if val >= 60:
            case_lines.append(f"                  case {idx}: interval = {val}; break;")

    if case_lines:
        cases_block = "\n".join(case_lines)
    else:
        cases_block = "                  default:\n                    break;"

    return f"""script:
  - id: manage_run_and_sleep
    mode: restart
    then:
      - if:
          condition:
            lambda: 'return id(ha_time).now().is_valid();'
          then:
            - lambda: |-
                int page = id(display_page);
                int interval = id(page_refresh_default_s);
                switch (page) {{
{cases_block}
                }}
                if (interval < 60) {{
                  interval = 60;
                }}
                ESP_LOGI("refresh", "Next refresh in %d seconds for page %d", interval, page);
            - delay: !lambda 'return std::chrono::seconds(interval);'
            - component.update: epaper_display
            - script.execute: manage_run_and_sleep
          else:
            - delay: 300s
            - component.update: epaper_display
            - script.execute: manage_run_and_sleep
"""


def _generate_display_block(device: DeviceConfig) -> str:
    """
    Generate the display: epaper_display block with a lambda that:
    - Reads current display_page.
    - Draws widgets belonging to the active page.
    - Uses DeviceConfig.orientation to pick rotation:
        - landscape -> rotation: 0
        - portrait  -> rotation: 90
    - DeviceConfig.dark_mode is advisory; widget-level color/invert decide actual draws.
    """
    lines: List[str] = []

    orientation = getattr(device, "orientation", "landscape")
    if orientation == "portrait":
        rotation = 90
    else:
        rotation = 0

    lines.append("display:")
    lines.append("  - platform: waveshare_epaper")
    lines.append("    id: epaper_display")
    lines.append("    model: 7.50inv2")
    lines.append("    cs_pin: GPIO10")
    lines.append("    dc_pin: GPIO11")
    lines.append("    reset_pin:")
    lines.append("      number: GPIO12")
    lines.append("      inverted: false")
    lines.append("    busy_pin:")
    lines.append("      number: GPIO13")
    lines.append("      inverted: true")
    lines.append("    update_interval: never")
    lines.append("    lambda: |-")
    lines.append("      it.fill(Color(0));")
    lines.append("")

    for page_index, page in enumerate(device.pages):
        _append_page_render(lines, page_index, page)

    return "\n".join(lines)


def _append_page_render(dst: List[str], page_index: int, page: PageConfig) -> None:
    indent = "      "
    dst.append(f'{indent}if (id(display_page) == {page_index}) {{')
    if not page.widgets:
        dst.append(f"{indent}  // Page {page_index}: no widgets configured.")
    else:
        for widget in page.widgets:
            _append_widget_render(dst, indent + "  ", widget)
    dst.append(f"{indent}}}")


def _resolve_font(props: dict) -> str:
    """Pick a font id based on optional font_size hint in widget props."""
    try:
        size = int(props.get("font_size", 0))
    except (TypeError, ValueError):
        size = 0

    if size <= 0:
        return "id(font_normal)"
    if size < 20:
        return "id(font_small)"
    if size < 26:
        return "id(font_normal)"
    return "id(font_header)"


def _resolve_font_by_size(size: int) -> str:
    """Pick a font id based on explicit font size value."""
    if size < 20:
        return "id(font_small)"
    if size < 26:
        return "id(font_normal)"
    return "id(font_header)"


def _append_widget_render(dst: List[str], indent: str, widget: WidgetConfig) -> None:
    """Render a single widget into display lambda C++ code.

    Unified styling semantics:
    - type: "text" / "label"
    - type: "sensor" / "sensor_text"
    - type: "shape_rect"
    - type: "shape_circle"
    - type: "line"
    - type: "image"
    - type: "history"
    """
    # Clamp to canvas
    x = max(0, min(widget.x, IMAGE_WIDTH))
    y = max(0, min(widget.y, IMAGE_HEIGHT))
    w = max(1, min(widget.width, IMAGE_WIDTH - x))
    h = max(1, min(widget.height, IMAGE_HEIGHT - y))

    wtype = (widget.type or "text").lower()
    props = widget.props or {}

    # Determine base color polarity from props.color and invert.
    base_color = (props.get("color") or "").lower()
    if base_color == "white":
        fg = "COLOR_ON"
    elif base_color == "gray":
        # For grayscale we still use COLOR_ON on b/w display; left for future patterns.
        fg = "COLOR_ON"
    else:
        # Default to "dark ink" style
        fg = "COLOR_OFF"

    if props.get("invert"):
        fg = "COLOR_OFF" if fg == "COLOR_ON" else "COLOR_ON"

    # Floating text (no box)
    if wtype in ("label", "text"):
        text = (props.get("text") or widget.title or "").replace('"', '\\"')
        if not text:
            return
        font = _resolve_font(props)
        # Add marker comment for parser
        dst.append(f'{indent}// widget:text id:{widget.id} type:text x:{x} y:{y} w:{w} h:{h} text:"{text}"')
        dst.append(f'{indent}it.print({x}, {y}, {font}, {fg}, "{text}");')
        return

    # Icon widget (MDI icon from font)
    if wtype == "icon":
        code = (props.get("code") or "F0595").strip().upper()
        # Validate code format (Fxxx)
        if not code.startswith("F") or len(code) != 5:
            code = "F0595"  # Default to weather-cloudy
        # Convert to unicode codepoint
        try:
            hex_val = int(code[1:], 16)
            codepoint = 0xF0000 + hex_val
            icon_char = chr(codepoint)
        except (ValueError, OverflowError):
            icon_char = chr(0xF0595)  # Fallback
        
        font_ref = props.get("font_ref", "font_mdi_medium")
        # Escape special characters
        escaped_char = icon_char.replace("\\", "\\\\").replace('"', '\\"')
        # Add marker comment for parser
        dst.append(f'{indent}// widget:icon id:{widget.id} type:icon x:{x} y:{y} w:{w} h:{h} code:{code}')
        dst.append(f'{indent}it.print({x}, {y}, id({font_ref}), {fg}, "{escaped_char}");')
        return

    # Sensor text (label + value from HA sensor)
    if wtype in ("sensor", "sensor_text"):
        entity_id = (widget.entity_id or "").strip()
        label = (widget.title or "").replace('"', '\\"')
        value_format = props.get("value_format", "label_value")
        label_font_size = int(props.get("label_font_size", 14) or 14)
        value_font_size = int(props.get("value_font_size", 20) or 20)
        
        if entity_id:
            # Generate safe ID from entity_id
            safe_id = entity_id.replace(".", "_").replace("-", "_")
            
            # Add marker comment for parser
            dst.append(f'{indent}// widget:sensor_text id:{widget.id} type:sensor_text x:{x} y:{y} w:{w} h:{h} ent:{entity_id} title:"{label}"')
            
            if value_format == "label_newline_value" and label:
                # Label on one line, value on another - use separate fonts
                label_font = _resolve_font_by_size(label_font_size)
                value_font = _resolve_font_by_size(value_font_size)
                # Print label
                dst.append(f'{indent}it.printf({x}, {y}, {label_font}, {fg}, "{label}");')
                # Print value below label (approximate line height)
                value_y = y + label_font_size + 4
                dst.append(f'{indent}it.printf({x}, {value_y}, {value_font}, {fg}, "%s", id({safe_id}).state.c_str());')
            elif value_format == "label_value" and label:
                # Inline format: "Label: Value" - use average size or value size
                font = _resolve_font_by_size(value_font_size)
                dst.append(f'{indent}it.printf({x}, {y}, {font}, {fg}, "{label}: %s", id({safe_id}).state.c_str());')
            else:
                # value_only or no label - just show value
                font = _resolve_font_by_size(value_font_size)
                dst.append(f'{indent}it.printf({x}, {y}, {font}, {fg}, "%s", id({safe_id}).state.c_str());')
        else:
            # No entity_id configured - show placeholder
            placeholder = label or "sensor"
            font = _resolve_font_by_size(value_font_size)
            # Add marker comment for parser
            dst.append(f'{indent}// widget:sensor_text id:{widget.id} type:sensor_text x:{x} y:{y} w:{w} h:{h} title:"{label}"')
            dst.append(f'{indent}// No entity_id configured for this sensor_text widget')
            dst.append(f'{indent}it.printf({x}, {y}, {font}, {fg}, "{placeholder}: N/A");')
        return

    # Rectangle / filled rectangle
    if wtype == "shape_rect":
        fill = bool(props.get("fill"))
        border_width = int(props.get("border_width", 1) or 1)
        opacity = int(props.get("opacity", 100) or 100)
        if fill:
            # For now opacity is advisory; could be mapped to patterns in future.
            dst.append(f"{indent}it.filled_rectangle({x}, {y}, {w}, {h}, {fg});")
            if border_width > 1:
                dst.append(f"{indent}it.rectangle({x}, {y}, {w}, {h}, {fg});")
        else:
            if border_width <= 1:
                dst.append(f"{indent}it.rectangle({x}, {y}, {w}, {h}, {fg});")
            else:
                # Approximate thicker border using multiple rectangles.
                dst.append(f"{indent}// rectangle with border_width={border_width}")
                dst.append(f"{indent}for (int i = 0; i < {border_width}; i++) {{")
                dst.append(
                    f"{indent}  it.rectangle({x}+i, {y}+i, {w}-2*i, {h}-2*i, {fg});"
                )
                dst.append(f"{indent}}}")
        return

    # Circle / filled circle (use width/height box)
    if wtype == "shape_circle":
        r = max(1, min(w, h) // 2)
        cx = x + w // 2
        cy = y + h // 2
        fill = bool(props.get("fill"))
        border_width = int(props.get("border_width", 1) or 1)
        if fill:
            dst.append(f"{indent}it.filled_circle({cx}, {cy}, {r}, {fg});")
            if border_width > 1:
                dst.append(f"{indent}it.circle({cx}, {cy}, {r}, {fg});")
        else:
            if border_width <= 1:
                dst.append(f"{indent}it.circle({cx}, {cy}, {r}, {fg});")
            else:
                dst.append(f"{indent}// circle with border_width={border_width}")
                dst.append(f"{indent}for (int i = 0; i < {border_width}; i++) {{")
                dst.append(f"{indent}  it.circle({cx}, {cy}, {r}-i, {fg});")
                dst.append(f"{indent}}}")
        return

    # Line: from (x,y) to (x+width,y+height) using width/height as dx/dy
    if wtype == "line":
        dx = w
        dy = h
        x2 = max(0, min(x + dx, IMAGE_WIDTH))
        y2 = max(0, min(y + dy, IMAGE_HEIGHT))
        stroke_width = int(props.get("stroke_width", 1) or 1)
        if stroke_width <= 1:
            dst.append(f"{indent}it.line({x}, {y}, {x2}, {y2}, {fg});")
        else:
            dst.append(f"{indent}// line with stroke_width={stroke_width}")
            dst.append(f"{indent}for (int i = 0; i < {stroke_width}; i++) {{")
            dst.append(f"{indent}  it.line({x}, {y}+i, {x2}, {y2}+i, {fg});")
            dst.append(f"{indent}}}")
        return

    # Static image widget: expects props.image_id to match an ESPHome image id
    if wtype == "image":
        image_id = (props.get("image_id") or "").strip()
        if image_id:
            dst.append(f"{indent}it.image({x}, {y}, id({image_id}));")
        else:
            dst.append(f"{indent}// image widget missing image_id at ({x},{y})")
        return

    # History widget: placeholder visualization; requires precomputed entity
    if wtype == "history":
        entity_id = (props.get("entity_id") or widget.entity_id or "").replace('"', '\\"')
        style = (props.get("style") or "bars").lower()
        label = entity_id or "history"
        font = _resolve_font(props)
        dst.append(f"{indent}// history widget for {entity_id}; expects external aggregation")
        dst.append(f'{indent}it.print({x}, {y}, {font}, {fg}, "{label}");')
        # Simple placeholder box/lines
        hx = x
        hy = y + 14
        hw = max(10, w)
        hh = max(6, h - 16)
        dst.append(f"{indent}it.rectangle({hx}, {hy}, {hw}, {hh}, {fg});")
        if style == "line":
            dst.append(f"{indent}it.line({hx+2}, {hy+hh-3}, {hx+hw-2}, {hy+3}, {fg});")
        else:
            dst.append(f"{indent}// draw simple bar-style segments as placeholder")
        return

    # Unknown type: emit comment for safety
    dst.append(f'{indent}// TODO: unsupported widget type "{widget.type}" at ({x},{y})')
    if wtype == "image":
        image_id = props.get("image_id")
        if image_id:
            dst.append(f"{indent}it.image({x}, {y}, id({image_id}));")
        else:
            dst.append(f"{indent}// image widget without image_id; nothing drawn")
        return

    # History graph widget (placeholder: renders a labeled box)
    if wtype == "history":
        title = (widget.title or "history").replace('"', '\\"')
        font = _resolve_font(props)
        dst.append(f"{indent}// History widget placeholder for {title}")
        dst.append(f"{indent}it.rectangle({x}, {y}, {w}, {h}, {fg});")
        dst.append(f"{indent}it.print({x}+2, {y}+2, {font}, {fg}, \"{title}\");")
        return

    # Fallback
    dst.append(f'{indent}// Unsupported widget type "{widget.type}" at ({x},{y},{w},{h})')