import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';

import {
    copyText,
    extractDisplayLambda,
    extractOpenDisplayPayload,
    extractUiOnlyYaml,
    formatOEPLServiceYaml,
    setTemporaryButtonLabel
} from '../../js/ui/snippet_manager_clipboard.js';

describe('snippet_manager_clipboard', () => {
    beforeEach(() => {
        document.body.innerHTML = '';
        vi.useFakeTimers();
    });

    afterEach(() => {
        vi.useRealTimers();
        vi.restoreAllMocks();
        vi.unstubAllGlobals();
    });

    it('uses the secure clipboard API when available', async () => {
        const writeText = vi.fn().mockResolvedValue(undefined);
        vi.stubGlobal('navigator', {
            clipboard: { writeText }
        });
        Object.defineProperty(window, 'isSecureContext', {
            configurable: true,
            value: true
        });

        await copyText('copied text');

        expect(writeText).toHaveBeenCalledWith('copied text');
        expect(document.querySelector('textarea')).toBeNull();
    });

    it('falls back to execCommand copy when the secure clipboard API rejects the write', async () => {
        const writeText = vi.fn().mockRejectedValue(new DOMException('denied', 'NotAllowedError'));
        vi.stubGlobal('navigator', {
            clipboard: { writeText }
        });
        Object.defineProperty(window, 'isSecureContext', {
            configurable: true,
            value: true
        });
        Object.defineProperty(document, 'execCommand', {
            configurable: true,
            value: vi.fn(() => true)
        });

        await copyText('fallback after denied permission');

        expect(writeText).toHaveBeenCalledWith('fallback after denied permission');
        expect(document.execCommand).toHaveBeenCalledWith('copy');
        expect(document.querySelector('textarea')).toBeNull();
    });

    it('falls back to execCommand copy when the secure clipboard API is unavailable', async () => {
        vi.stubGlobal('navigator', {});
        Object.defineProperty(window, 'isSecureContext', {
            configurable: true,
            value: false
        });
        Object.defineProperty(document, 'execCommand', {
            configurable: true,
            value: vi.fn(() => true)
        });

        await copyText('fallback text');

        expect(document.execCommand).toHaveBeenCalledWith('copy');
        expect(document.querySelector('textarea')).toBeNull();
    });

    it('throws when the fallback copy command is rejected', async () => {
        vi.stubGlobal('navigator', {});
        Object.defineProperty(window, 'isSecureContext', {
            configurable: true,
            value: false
        });
        Object.defineProperty(document, 'execCommand', {
            configurable: true,
            value: vi.fn(() => false)
        });

        await expect(copyText('denied')).rejects.toThrow('Copy command was rejected');
        expect(document.querySelector('textarea')).toBeNull();
    });

    it('temporarily swaps a button label and restores the original width and contents', () => {
        const button = document.createElement('button');
        button.innerHTML = '<span class="mdi mdi-content-copy"></span>Copy';
        document.body.appendChild(button);
        Object.defineProperty(button, 'offsetWidth', {
            configurable: true,
            value: 82
        });

        setTemporaryButtonLabel(button, 'Copied', 500);
        expect(button.textContent).toBe('Copied');
        expect(button.style.minWidth).toBe('82px');

        vi.advanceTimersByTime(500);
        expect(button.textContent).toBe('Copy');
        expect(button.querySelector('.mdi-content-copy')).not.toBeNull();
        expect(button.style.minWidth).toBe('');
    });

    it('extracts and de-indents the display lambda section from YAML output', () => {
        const yaml = `
esphome:
  name: demo
display:
  - platform: waveshare_epaper
    lambda: |-
      it.print(0, 0, id(font_small), "Hello");
      it.printf(10, 20, id(font_small), "%s", "World");
sensor:
  - platform: wifi_signal
`;

        expect(extractDisplayLambda(yaml)).toBe(
            'it.print(0, 0, id(font_small), "Hello");\n' +
            'it.printf(10, 20, id(font_small), "%s", "World");'
        );
    });

    it('rejects YAML outputs without a display section or with an empty lambda', () => {
        expect(() => extractDisplayLambda('sensor:\n  - platform: wifi_signal\n')).toThrow('No display section found in output');
        expect(() => extractDisplayLambda('display:\n  - platform: ssd1306\n    lambda: |-\n')).toThrow('Lambda appears to be empty');
    });

    it('extracts UI YAML while removing hardware and system root sections', () => {
        const yaml = [
            '# ESPHome YAML - Generated by ESPHome Designer',
            'esphome:',
            '  name: demo',
            'esp32:',
            '  board: esp32-s3-devkitc-1',
            'wifi:',
            '  ssid: !secret wifi_ssid',
            '',
            'display:',
            '  - platform: ili9xxx',
            '    id: main_display',
            '',
            '# esp8266: # (Auto-commented)',
            '#   board: nodemcuv2',
            '#   framework:',
            '#     version: recommended',
            '',
            'lvgl:',
            '  pages: []',
            '',
            'font:',
            '  - file: gfonts://Roboto',
            '    id: font_small',
            '',
            'sensor:',
            '  - platform: homeassistant',
            '    entity_id: sensor.temperature'
        ].join('\n');

        const result = extractUiOnlyYaml(yaml);

        expect(result).toContain('display:');
        expect(result).toContain('lvgl:');
        expect(result).toContain('font:');
        expect(result).toContain('sensor:');
        expect(result).not.toContain('esphome:');
        expect(result).not.toContain('name: demo');
        expect(result).not.toContain('esp32:');
        expect(result).not.toContain('wifi:');
        expect(result).not.toContain('# esp8266:');
        expect(result).not.toContain('nodemcuv2');
    });

    it('rejects UI YAML extraction when only hardware and system sections remain', () => {
        expect(() => extractUiOnlyYaml('esphome:\n  name: demo\nwifi:\n  ssid: test\n')).toThrow(
            'No UI YAML remains after removing hardware/system sections'
        );
    });

    it('formats OEPL service YAML with defaults and caller overrides', () => {
        const serviceData = {
            service: 'open_epaper_link.drawcustom',
            target: {},
            data: {
                background: 'white',
                rotate: 0,
                ttl: 120,
                payload: {
                    lines: [{ text: 'Hello' }]
                }
            }
        };

        const formatted = formatOEPLServiceYaml(serviceData, {
            oeplEntityId: 'open_epaper_link.1234567890abcdef',
            oeplDither: 1
        });

        expect(serviceData.target.entity_id).toBe('open_epaper_link.1234567890abcdef');
        expect(serviceData.data.dither).toBe(1);
        expect(formatted).toContain('service: open_epaper_link.drawcustom');
        expect(formatted).toContain('entity_id: open_epaper_link.1234567890abcdef');
        expect(formatted).toContain('dither: 1');
        expect(formatted).toContain('"text":"Hello"');
    });

    it('extracts payload block from OpenDisplay YAML', () => {
        const odpYaml = [
            'action: opendisplay.drawcustom',
            'target:',
            '  device_id: "95b2d0433f2c26d08088d6296a00a70d"',
            'data:',
            '  background: "white"',
            '  rotate: 0',
            '  dither: 2',
            '  ttl: 60',
            '  refresh_type: "0"',
            '  dry-run: false',
            '  payload:',
            '    # id: widget_0',
            '    - type: "text"',
            '      x: 10',
            '      y: 20',
            '      value: "hello"',
            '    - type: "line"',
            '      stroke_width: 1'
        ].join('\n');

        const result = extractOpenDisplayPayload(odpYaml);
        expect(result).toBe([
            'payload:',
            '  # id: widget_0',
            '  - type: "text"',
            '    x: 10',
            '    y: 20',
            '    value: "hello"',
            '  - type: "line"',
            '    stroke_width: 1'
        ].join('\n'));
    });

    it('handles empty or missing payload in extractOpenDisplayPayload', () => {
        expect(extractOpenDisplayPayload('')).toBe('payload: []');
        expect(extractOpenDisplayPayload('action: test\ndata:\n  payload: []')).toBe('payload: []');
        expect(extractOpenDisplayPayload('action: test\nno_payload: true')).toBe('payload: []');
    });

    it('extracts payload from OEPL JSON in extractOpenDisplayPayload', () => {
        const jsonText = JSON.stringify({
            service: 'open_epaper_link.drawcustom',
            target: { entity_id: 'sensor.test' },
            data: {
                payload: [{ type: 'text', value: 'hello' }]
            }
        });
        const result = extractOpenDisplayPayload(jsonText);
        expect(JSON.parse(result)).toEqual([{ type: 'text', value: 'hello' }]);

        // Direct top-level payload in JSON
        const directJson = JSON.stringify({
            payload: [{ type: 'icon', value: 'mdi:home' }]
        });
        expect(JSON.parse(extractOpenDisplayPayload(directJson))).toEqual([{ type: 'icon', value: 'mdi:home' }]);

        // JSON without payload fallback to YAML
        expect(extractOpenDisplayPayload('{"other": 123}')).toBe('payload: []');

        // Invalid JSON starting with { falls back to YAML
        expect(extractOpenDisplayPayload('{ not valid json')).toBe('payload: []');
    });

    it('handles blank lines and following outer blocks when extracting payload', () => {
        const yamlWithBlanksAndNextBlock = [
            'action: opendisplay.drawcustom',
            'data:',
            '  payload:',
            '    - type: text',
            '',
            '    - type: icon',
            'following_key: value'
        ].join('\n');

        const extracted = extractOpenDisplayPayload(yamlWithBlanksAndNextBlock);
        expect(extracted).toBe([
            'payload:',
            '  - type: text',
            '',
            '  - type: icon'
        ].join('\n'));
    });
});
