import { describe, it, expect } from 'vitest';
import { parseHardwareRecipeClientSide } from '../../js/io/hardware_profile_sources.js';
import geekMagicMiniYaml from '../../hardware/geekmagic-mini-esp8266.yaml?raw';
import m5stackTab5Yaml from '../../hardware/m5stack-tab5.yaml?raw';
import sunton2432s028Yaml from '../../hardware/sunton-esp32-2432s028.yaml?raw';
import sunton2432s028RYaml from '../../hardware/sunton-esp32-2432s028R.yaml?raw';

describe('hardware_profile_sources', () => {
    it('parses the ViewDisplay round TFT knob recipe metadata and features', () => {
        const yaml = `
# Name: ViewDisplay ESP32 Round TFT Knob 2.1" UEDX48480021-MD80ET
# Resolution: 480x480
# Shape: round

esp32:
  board: esp32-s3-devkitc-1

psram:
  mode: octal
  speed: 80MHz

display:
  - platform: st7701s
    id: my_display
    dimensions:
      width: 480
      height: 480
    # __LAMBDA_PLACEHOLDER__

touchscreen:
  - platform: cst816
    id: my_touchscreen
`;

        const profile = parseHardwareRecipeClientSide(yaml, 'viewdisplay-esp32-s3-uedx48480021.yaml');

        expect(profile.name).toBe('ViewDisplay ESP32 Round TFT Knob 2.1" UEDX48480021-MD80ET');
        expect(profile.shape).toBe('round');
        expect(profile.resolution).toEqual({ width: 480, height: 480 });
        expect(profile.board).toBe('esp32-s3-devkitc-1');
        expect(profile.displayPlatform).toBe('st7701s');
        expect(profile.features.psram).toBe(true);
        expect(profile.features.lcd).toBe(true);
        expect(profile.features.touch).toBe(true);
        expect(profile.features.epaper).toBe(false);
        expect(profile.hardwarePackage).toBeUndefined();
    });

    it('detects ESP32-P4 boards from esp32 variants and board ids', () => {
        const yaml = `
# Name: Waveshare ESP32-P4 Panel
# Resolution: 800x480
# Shape: rect

esp32:
  board: esp32-p4-evboard
  variant: esp32p4

display:
  - platform: ili9xxx
    id: my_display
`;

        const profile = parseHardwareRecipeClientSide(yaml, 'waveshare-esp32-p4.yaml');

        expect(profile.chip).toBe('esp32-p4');
        expect(profile.board).toBe('esp32-p4-evboard');
        expect(profile.displayPlatform).toBe('ili9xxx');
    });

    it('parses the GeekMagic Mini ESP8266 bundled recipe', () => {
        expect(geekMagicMiniYaml).toContain('# ESPHome YAML - Generated by ESPHome Designer');
        expect(geekMagicMiniYaml).toContain('# SETUP INSTRUCTIONS:');
        expect(geekMagicMiniYaml).toContain('# CAPTIVE PORTAL:');

        const profile = parseHardwareRecipeClientSide(geekMagicMiniYaml, 'geekmagic-mini-esp8266.yaml');

        expect(profile.name).toBe('GeekMagic Mini (ESP8266)');
        expect(profile.resolution).toEqual({ width: 240, height: 240 });
        expect(profile.chip).toBe('esp8266');
        expect(profile.board).toBe('esp01_1m');
        expect(profile.displayPlatform).toBe('mipi_spi');
        expect(profile.displayModel).toBe('ST7789V');
        expect(profile.updateInterval).toBe('60s');
        expect(profile.invertColors).toBe(true);
        expect(profile.features.touch).toBe(false);
    });

    it('parses the M5Stack Tab5 bundled recipe', () => {
        expect(m5stackTab5Yaml).toContain('# ESPHome YAML - Generated by ESPHome Designer');
        expect(m5stackTab5Yaml).toContain('# SETUP INSTRUCTIONS:');
        expect(m5stackTab5Yaml).toContain('# CAPTIVE PORTAL:');

        const profile = parseHardwareRecipeClientSide(m5stackTab5Yaml, 'm5stack-tab5.yaml');

        expect(profile.name).toBe('M5Stack Tab5');
        expect(profile.resolution).toEqual({ width: 1280, height: 720 });
        expect(profile.chip).toBe('esp32-p4');
        expect(profile.board).toBe('esp32-p4-evboard');
        expect(profile.displayPlatform).toBe('mipi_dsi');
        expect(profile.displayModel).toBe('M5STACK-TAB5-V2');
        expect(profile.features.psram).toBe(true);
        expect(profile.features.touch).toBe(true);
        expect(profile.features.lcd).toBe(true);
    });

    it('keeps Sunton 2432S028 package dimensions aligned with the landscape transform', () => {
        for (const yaml of [sunton2432s028Yaml, sunton2432s028RYaml]) {
            expect(yaml).toContain('swap_xy: true');
            expect(yaml).toContain(`dimensions:
      height: 240
      width: 320`);
        }
    });
});
