name: Hassfest

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hassfest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Run hassfest
        run: >
          docker run --rm
          -v "${{ github.workspace }}:/github/workspace"
          ghcr.io/home-assistant/hassfest
          --core-path=/usr/src/homeassistant
          --integration-path
          /github/workspace/custom_components/esphome_designer
